# Generated by Django 5.2.1 on 2025-06-01 14:42

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(validators=[posts.validators.BadWordValidator(bad_words=['bad_word_1', 'bad_word_2'])])),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('py', 'Python'), ('js', 'JAvaScript'), ('c', 'C'), ('cpp', 'C++'), ('other', 'Other')], default='other', max_length=20)),
            ],
        ),
    ]
